DROP TABLE IF EXISTS Categories;
GO;

CREATE TABLE Categories (
    Id        UNIQUEIDENTIFIER  PRIMARY KEY,
    Name      NVARCHAR(64)      NOT NULL,
    CreatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    OwnerId    UNIQUEIDENTIFIER  NOT NULL,
    
    CONSTRAINT FK_CategoriesAuthor FOREIGN KEY (OwnerId) REFERENCES Users(Id),
);