DROP TABLE IF EXISTS Users;
GO;

CREATE TABLE Users
(
    Id           UNIQUEIDENTIFIER  PRIMARY KEY,
    Username     NVARCHAR(64)      NOT NULL,
    Email        NVARCHAR(64)      NOT NULL,
    ImageUrl     NVARCHAR(MAX),
    PasswordHash VARBINARY(64)     NOT NULL,
    PasswordSalt VARBINARY(128)    NOT NULL,
    CreatedAt    DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt    DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
);