DROP TABLE Calendars;
GO;

CREATE TABLE Calendars (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(64) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    UpdatedAt DATETIMEOFFSET NOT NULL,
    Author UNIQUEIDENTIFIER NOT NULL,
    
    CONSTRAINT FK_CalendarsAuthor FOREIGN KEY (Author) REFERENCES Users(Id)
);