DROP TABLE Categories;
GO;

CREATE TABLE Categories (
    Id        UNIQUEIDENTIFIER  PRIMARY KEY,
    Name      NVARCHAR(64)      NOT NULL,
    CreatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    Author    UNIQUEIDENTIFIER  NOT NULL,
    
    CONSTRAINT FK_CategoriesAuthor FOREIGN KEY (Author) REFERENCES Users(Id),
);