DROP TABLE Calendars;
GO;

CREATE TABLE Calendars (
    Id        UNIQUEIDENTIFIER  PRIMARY KEY,
    Name      NVARCHAR(64)      NOT NULL,
    CreatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET    NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    OwnerId    UNIQUEIDENTIFIER  NOT NULL,
    
    CONSTRAINT FK_CalendarsAuthor FOREIGN KEY (OwnerId) REFERENCES Users(Id),
);